URLから拡張子を除去 closed #20
Dan344/www.syake.co.jp pull request #21
Opened 2017-11-07 10:35 UTC by ncaq

やったこと

* 最新のstackageに
* hpackを使用
* yarnを使用
* パッケージの間違った値を修正
* haskellコードフォーマット
* htmlコードフォーマット
* yarnの警告を除去
* navを今のbootstrapでも崩れないように変更
* 404ページに追記
* **URLから`.html`拡張子を削除**

色々やりましたが,大規模な破壊的な変更はURLからの拡張子削除のみのはずです.

公にするURLに拡張子は付けるべきではなく,本来公開する前に指摘するべきでした.
指摘が大変遅れてしまって申し訳ないです.

自分のサイトのURLを考えてそう言えばこのサイトはどうなっていたっけと思って見て,
思わずガッってやってしまいました.

このサイトはまだあまり拡散されていないため,まだURLの変更が間に合うと判断しています.

一応確認はしましたが,URLの拡張子除去以外に破壊的変更が無いか確認をお願いします.

問題がなければデプロイをお願いします.

2017-11-07 11:04 UTC, moso344 requested changes
ありがとうございます 👍 


一部ニュースリリースは、ニュースサイト等でリンクされているので、既存のページはなるべくリダイレクト出来るようにしたいです。

更新の度にバケットを丸々入れ替えているので、S3によるリダイレクトは使えないので、リダイレクトのhtmlを吐くようにしておきたいですね

2017-11-07 11:22 UTC, moso344 requested changes

2017-11-07 11:22 UTC, Dan344 commented on release/2.md
> -<https://www.syake.co.jp/game/ghostus/download.html>
既存のニュースリリースは基本的に変更せずに残しておくのが良いと思います。
release以下のmarkdownではurlの表記をそのままにしておいてリダイレクト出来るようにした方が良さそうです

2017-11-07 11:22 UTC, Dan344 commented on release/2.md
> -| β版           | <https://www.syake.co.jp/game/ghostus/download.html>
同じく、そのままの方が良さそう

2017-11-07 11:44 UTC, Dan344 commented
[バケット自体にリダイレクトのルールをxmlで記述できるらしい](http://docs.aws.amazon.com/ja_jp/AmazonS3/latest/dev/how-to-page-redirect.html)けど、xmlの内容をリポジトリに含めて、デプロイ時に自動で読み込めるようにするとかできないのかな。

2017-11-08 01:08 UTC, Dan344 commented
s3のリダイレクトルール。こんな感じで行けそう

```xml
<RoutingRules>
    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>release/1.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <HostName>www.syake.co.jp</HostName>
            <ReplaceKeyWith>release/1</ReplaceKeyWith>
            <HttpRedirectCode>301</HttpRedirectCode>
        </Redirect>
    </RoutingRule>

    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>release/2.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <HostName>www.syake.co.jp</HostName>
            <ReplaceKeyWith>release/2</ReplaceKeyWith>
            <HttpRedirectCode>301</HttpRedirectCode>
        </Redirect>
    </RoutingRule>

    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>release/3.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <HostName>www.syake.co.jp</HostName>
            <ReplaceKeyWith>release/3</ReplaceKeyWith>
            <HttpRedirectCode>301</HttpRedirectCode>
        </Redirect>
    </RoutingRule>

    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>/corporation-profile.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <HostName>www.syake.co.jp</HostName>
            <ReplaceKeyWith>/corporation-profile</ReplaceKeyWith>
            <HttpRedirectCode>301</HttpRedirectCode>
        </Redirect>
    </RoutingRule>

    <RoutingRule>
        <Condition>
            <KeyPrefixEquals>/game/ghostus/download.html</KeyPrefixEquals>
        </Condition>
        <Redirect>
            <HostName>www.syake.co.jp</HostName>
            <ReplaceKeyWith>/game/ghostus/download</ReplaceKeyWith>
            <HttpRedirectCode>301</HttpRedirectCode>
        </Redirect>
    </RoutingRule>
</RoutingRules>
```

2017-11-08 01:08 UTC, Dan344 commented
正規表現は使えないっぽい？

2017-11-08 10:28 UTC, merged

2017-11-08 10:46 UTC, Dan344 commented
ちなみに、URLについて、
`www.syake.co.jp/hoge` と `www.syake.co.jp/hoge/` のどっちが良いんでしょう。syakerakeは最後のスラッシュ無かったので、リダイレクトの設定ではスラッシュ無くしてましたが、プルリクの変更ではスラッシュついてましたね

2017-11-13 06:26 UTC, ncaq commented
> www.syake.co.jp/hoge と www.syake.co.jp/hoge/ のどっちが良いんでしょう

自分も割と悩みますが,今回はあくまで`index.html`を表示してもらう仕組みになっているので,スラッシュあった方が良いのかも
まあどっちでも良いですね

2017-11-13 06:30 UTC, ncaq commented on release/2.md
> -<https://www.syake.co.jp/game/ghostus/download.html>
リダイレクトは暫定的な処置なので,変更できるものは変更しておいた方が良いと思います…

2017-11-13 06:38 UTC, Dan344 commented on release/2.md
> -<https://www.syake.co.jp/game/ghostus/download.html>
プレスリリースについては、「既に発表済みのもの」という認識なので、後から変更を加えるのは好ましくないと考えています。プレスリリース以外のページであれば、変更するのが正しいと思います

2017-11-13 07:21 UTC, ncaq commented on release/2.md
> -<https://www.syake.co.jp/game/ghostus/download.html>
私は変更がgitに残るので別に卑怯な行いなどとは思いませんが,まあそういうポリシーがあるなら仕方がないですね

2017-11-13 07:25 UTC, Dan344 commented on release/2.md
> -<https://www.syake.co.jp/game/ghostus/download.html>
ニュースサイト等だと、リリースの文面を一部そのまま貼り付けている所もあるので、実際のリリースのニュース記事で表示がズレたりする可能性が高いので、多少の気持ち悪さはありますが、仕方ないかなという感じです。

> 変更がgitに残るので別に卑怯な行いなどとは思いません

確かにそうですね。