url構造を書き換え,tidy htmlによるチェック
Dan344/www.syake.co.jp pull request #6
Opened 2017-06-26 05:52 UTC by ncaq

2017-06-26 06:35 UTC, moso344 requested changes
tidyがerrorになって動作確認が出来ていない

2017-06-26 06:35 UTC, Dan344 commented on corporation-profile.md
> +| 取引銀行   | 三井住友銀行 生田支店<br />川崎信用金庫 登戸支店
html5、`<br/>` じゃなくて `<br>` で良かった気もするんですよね

2017-06-26 06:35 UTC, Dan344 commented on release/1.md
> +GHOSTUS公式ページ: <https://www.syake.co.jp/game/ghostus>
`<>` でurlを囲んでしまうと、 ogpのdescriptionに設定する際に正規表現でhtmlタグを除去しているので、これだと消えそう(未確認)

2017-06-26 06:35 UTC, Dan344 commented on release/1.md
> +SYAKEARAKEティザーサイト: <http://www.syakerake.jp>
同上

2017-06-26 06:35 UTC, Dan344 commented on release/1.md
> +SYAKEARAKEティザーサイト: <http://www.syakerake.jp>
それとも、markdownだとこういうのが一般的？

2017-06-26 06:35 UTC, Dan344 commented on release/2.md
> +| 販売           | [SYAKERAKE](http://www.syakerake.jp)
ニュースリリースは直接URLが見えたほうが良いので、元の表記か `[SYAKERAKE(http://www.syakerake.jp)](http://www.syakerake.jp)` 等が良いかも

2017-06-26 06:35 UTC, Dan344 commented on site.hs
> -    reg = mkRegex "<(\"[^\"]*\"|\'[^\']*\'|[^\'\">])*>"
動かせていないからわからないけど、htmlタグが`og:description` に紛れ混まなければ良いです

2017-06-26 06:35 UTC, Dan344 commented on site.hs
> +                              ] bo)
tidy入れてみたけど、うまく動かない(謎

```
Removing _site...
Removing _cache...
Removing _cache/tmp...
Initialising...
  Creating store...
  Creating provider...
  Running rules...
Checking for out-of-date items
Compiling
  updated templates/default.html
  [ERROR] Hakyll.Core.UnixFilter.unixFilterWith: tidy --drop-empty-elements n --tidy-mark n --wrap 0 -indent gave exit code 2

```

npmの [`tidy-html5`](https://www.npmjs.com/package/tidy-html5) とかはどうでしょう

2017-06-26 07:25 UTC, ncaq commented on corporation-profile.md
> +| 取引銀行   | 三井住友銀行 生田支店<br />川崎信用金庫 登戸支店
html5はそれでも良いんですが,feedはXMLなのでダメで,feedを出力することを考えると全部閉じておいたほうが考えなくて楽です

2017-06-26 07:26 UTC, ncaq commented on release/1.md
> +GHOSTUS公式ページ: <https://www.syake.co.jp/game/ghostus>
そのへんpandocに変換させてぶち壊すことにしました

2017-06-26 07:27 UTC, ncaq commented on release/1.md
> +SYAKEARAKEティザーサイト: <http://www.syakerake.jp>
これはpandoc markdown文法のURLそのままリンクにする奴なんです

2017-06-26 07:27 UTC, ncaq commented on release/2.md
> +| 販売           | [SYAKERAKE](http://www.syakerake.jp)
なるほど,どちらかに書き換えておいて欲しいです

2017-06-26 07:29 UTC, ncaq commented on site.hs
> +                              ] bo)
んー,tidy-html5をemscriptenでコンパイルしたものなので,同じように動くはずなんですよね…`rebuild -v`でエラーログを見せてみてくれませんか

2017-06-26 10:25 UTC, Dan344 commented on corporation-profile.md
> +| 取引銀行   | 三井住友銀行 生田支店<br />川崎信用金庫 登戸支店
圧倒的把握。了解です

2017-06-26 10:25 UTC, Dan344 commented on release/1.md
> +GHOSTUS公式ページ: <https://www.syake.co.jp/game/ghostus>
了解

2017-06-26 10:25 UTC, Dan344 commented on release/1.md
> +SYAKEARAKEティザーサイト: <http://www.syakerake.jp>
なるほど。了解

2017-06-26 10:25 UTC, Dan344 commented on release/2.md
> +| 販売           | [SYAKERAKE](http://www.syakerake.jp)
適当になおしておきます

2017-06-26 10:25 UTC, Dan344 commented on site.hs
> +                              ] bo)
入れたのは、 `apt-get install tidy` です。

> npmの [`tidy-html5`](https://www.npmjs.com/package/tidy-html5) とかはどうでしょう

これは、 `npm i` で上手くいくように出来ないかという提案の意図でした。

ログは下記(正直わからん)

```
dan@www.syake.co.jp (ncaq=)$ stack exec site rebuild -v
Version 1.4.0, Git revision 5986498a9d1073e8d58c79ec1302bb2a7847a396 (4642 commits) x86_64 hpack-0.17.0
2017-06-26 19:22:12.618187: [debug] Checking for project config at: /home/dan/www.syake.co.jp/stack.yaml
@(Stack/Config.hs:935:9)
2017-06-26 19:22:12.618442: [debug] Loading project config file stack.yaml
@(Stack/Config.hs:960:13)
2017-06-26 19:22:12.620325: [debug] Trying to decode /home/dan/.stack/build-plan-cache/x86_64-linux/lts-8.20.cache
@(Data/Store/VersionTagged.hs:68:5)
2017-06-26 19:22:12.634251: [debug] Success decoding /home/dan/.stack/build-plan-cache/x86_64-linux/lts-8.20.cache
@(Data/Store/VersionTagged.hs:72:13)
2017-06-26 19:22:12.638862: [debug] Run process: /sbin/ldconfig -p
@(System/Process/Read.hs:306:3)
2017-06-26 19:22:12.641456: [debug] Process finished in 2ms: /sbin/ldconfig -p
@(System/Process/Read.hs:306:3)
2017-06-26 19:22:12.641683: [debug] Run process: /usr/bin/gcc -v
@(System/Process/Read.hs:306:3)
2017-06-26 19:22:12.643124: [debug] Process finished in 1ms: /usr/bin/gcc -v
@(System/Process/Read.hs:306:3)
2017-06-26 19:22:12.643241: [debug] PIE enabled
@(Stack/Setup.hs:577:17)
2017-06-26 19:22:12.648795: [debug] Found shared library libtinfo.so.5 in 'ldconfig -p' output
@(Stack/Setup.hs:553:29)
2017-06-26 19:22:12.649170: [debug] Did not find shared library libtinfo.so.6
@(Stack/Setup.hs:567:38)
2017-06-26 19:22:12.649254: [debug] Did not find shared library libncursesw.so.6
@(Stack/Setup.hs:567:38)
2017-06-26 19:22:12.649314: [debug] Found shared library libgmp.so.10 in 'ldconfig -p' output
@(Stack/Setup.hs:553:29)
2017-06-26 19:22:12.649384: [debug] Did not find shared library libgmp.so.3
@(Stack/Setup.hs:567:38)
2017-06-26 19:22:12.649435: [debug] Using standard GHC build
@(Stack/Setup.hs:600:9)
2017-06-26 19:22:12.649795: [debug] Getting Cabal package version
@(Stack/GhcPkg.hs:189:5)
2017-06-26 19:22:12.649923: [debug] Run process: /home/dan/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc-pkg --no-user-package-db field --simple-output Cabal version
@(System/Process/Read.hs:306:3)
2017-06-26 19:22:12.650884: [debug] Getting global package database location
@(Stack/GhcPkg.hs:55:5)
2017-06-26 19:22:12.650999: [debug] Run process: /home/dan/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc-pkg --no-user-package-db list --global
@(System/Process/Read.hs:306:3)
2017-06-26 19:22:12.652119: [debug] Asking GHC for its version
@(Stack/Setup/Installed.hs:103:13)
2017-06-26 19:22:12.652354: [debug] Run process: /home/dan/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc --numeric-version
@(System/Process/Read.hs:306:3)
2017-06-26 19:22:12.665658: [debug] Process finished in 15ms: /home/dan/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc-pkg --no-user-package-db field --simple-output Cabal version
@(System/Process/Read.hs:306:3)
2017-06-26 19:22:12.666158: [debug] Process finished in 15ms: /home/dan/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc-pkg --no-user-package-db list --global
@(System/Process/Read.hs:306:3)
2017-06-26 19:22:12.707951: [debug] Process finished in 55ms: /home/dan/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc --numeric-version
@(System/Process/Read.hs:306:3)
2017-06-26 19:22:12.708198: [debug] Resolving package entries
@(Stack/Setup.hs:254:5)
2017-06-26 19:22:12.708709: [debug] Starting to execute command inside EnvConfig
@(Stack/Runners.hs:166:18)
2017-06-26 19:22:12.708993: [debug] Run process: /home/dan/www.syake.co.jp/.stack-work/install/x86_64-linux/lts-8.20/8.0.2/bin/site rebuild
@(Stack/Exec.hs:67:5)
Removing _site...
Removing _cache...
Removing _cache/tmp...
Initialising...
  Creating store...
  Creating provider...
  Running rules...
Checking for out-of-date items
Compiling
  updated templates/default.html
  [ERROR] Hakyll.Core.UnixFilter.unixFilterWith: tidy --drop-empty-elements n --tidy-mark n --wrap 0 -indent gave exit code 2
```

2017-06-26 12:13 UTC, ncaq commented on site.hs
> +                              ] bo)
何も吐いてないですね,tidy自体これ使えるようになってるのかな?よくわからん

2017-06-27 11:50 UTC, moso344 reviewed
疑問等

2017-06-27 11:50 UTC, Dan344 commented on release/1.md
> -<!--more-->
teaser、これ使って指定したい感ある

2017-06-27 11:50 UTC, Dan344 commented on release/1.md
> -|:--|:--|
テーブル壊れてる

2017-06-27 11:50 UTC, Dan344 commented on site.hs
> +  where teaserField' key snapshot = field key $ \item -> take 100 . stripTags . trans . itemBody <$> loadSnapshot (itemIdentifier item) snapshot
teaser、100文字にしてしまっています？
個人的には切りの良いところまで表示してしまいたいので、 `<!--more-->` が良いのではという気持ちがあります

2017-06-27 11:50 UTC, Dan344 commented on site.hs
> +                              ] bo)
apt-getのtidyじゃなくて、 [tidy-html5](https://github.com/htacg/tidy-html5/blob/next/README/BUILD.md)じゃないと駄目だったようです。動きました

2017-06-27 11:50 UTC, Dan344 commented on templates/default.html
> +                            </p>
流儀をわかっていないマンなのですが、

- 画像と会社名のpタグ分ける必要ってあります？
- `&copy;` よりも `©` の方が良いの？

2017-06-27 11:50 UTC, Dan344 commented on release/2.md
> +![ghostus-instruction](/image/release/ghostus-instruction.png)
`![ghostus-instruction](/image/release/ghostus-instruction.png)` の表記が正しいのはわかるのですが、figcaptionが表示されて冗長に見えるんですよね。なので、 `![](/image/release/ghostus-instruction.png)` のような感じにしていました。

pandocの設定で変えられたりしますかね。ダメそうならcssで無理やり非表示にする等しようかと思います

2017-06-27 11:54 UTC, Dan344 commented on site.hs
> +  where teaserField' key snapshot = field key $ \item -> take 100 . stripTags . trans . itemBody <$> loadSnapshot (itemIdentifier item) snapshot
あと、各記事

```html
        $if(description)$
        <meta property="og:description" content="$description$">
        $else$
        <meta property="og:description" content="Syake株式会社は「任価」(任意の時期・金額・回数による支払い)による投稿型PCゲーム販売サイト「SYAKERAKE」の運営及びゲーム開発を行っています">
        $endif$

```

みたいにして`og:description` 切り替えていたので、現在、descriptionがなくなって、全部同じ内容になってしまっている

2017-06-27 12:00 UTC, Dan344 commented
何故かpushがrejectされる

2017-06-27 12:15 UTC, Dan344 commented
masterからPull Request来てるからかしら。わからん

2017-06-27 12:31 UTC, Dan344 commented
push出来たわ

2017-06-27 12:55 UTC, Dan344 commented on site.hs
> +  where teaserField' key snapshot = field key $ \item -> take 100 . stripTags . trans . itemBody <$> loadSnapshot (itemIdentifier item) snapshot
それとも、descriptionは自動でやろうとせず、各記事にyamlで書くか

2017-06-28 10:11 UTC, Dan344 commented on site.hs
> +  where teaserField' key snapshot = field key $ \item -> take 100 . stripTags . trans . itemBody <$> loadSnapshot (itemIdentifier item) snapshot
ここらへんどうしましょうか。個人的には

- `<!--more-->` で指定
- metaデータに descriptionを指定する

のどちらかが良いと思っています。
`og:image` なんかを記事ごとに指定するのも、metaデータに画像のurlを書く事にしようと考えているので、metaデータとして書くでも良いかなと考えています

2017-06-28 10:13 UTC, Dan344 commented on templates/default.html
> +                            </p>
❔

2017-06-28 15:14 UTC, merged

2017-06-28 15:15 UTC, Dan344 commented
とりあえず、こちらの解釈で直してMergeしてしまいました。
おそらく納得行かない部分があると思うので、またPull Request下さい :octocat: